// <auto-generated />
using BuscandoMiTrago.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuscandoMiTrago.Migrations
{
    [DbContext(typeof(CoctelDBContext))]
    [Migration("20240806230105_first-migration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuscandoMiTrago.Models.CoctelFavorito", b =>
                {
                    b.Property<int>("idDrink")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDrink");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDrink"));

                    b.Property<string>("strDrink")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("strDrink");

                    b.Property<string>("strDrinkThumb")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("strDrinkThumb");

                    b.HasKey("idDrink");

                    b.ToTable("CoctelFavorito", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
